# requires gcr-trigger on git tag
steps:

  - name: docker
    id: app-forwarder-build
    waitFor: ['-']
    entrypoint: '/bin/sh'
    dir: 'app-forwarder'
    args:
      - -c
      - 'docker build -t gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA . &&
         docker tag gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA gcr.io/$PROJECT_ID/app-forwarder:$TAG_NAME &&
         docker tag gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA gcr.io/$PROJECT_ID/app-forwarder:latest'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    waitFor: [app-forwarder-build]
    entrypoint: gcloud
    args:
      - 'run deploy app-forwarder --image gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA --region europe-west4 --platform managed'

  - name: docker
    id: data-processor-build
    waitFor: ['-']
    entrypoint: '/bin/sh'
    dir: 'data-processor'
    args:
      - -c
      - 'docker build -t gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA . &&
         docker tag gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA gcr.io/$PROJECT_ID/data-processor:$TAG_NAME &&
         docker tag gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA gcr.io/$PROJECT_ID/data-processor:latest'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    waitFor: [data-processor-build]
    entrypoint: gcloud
    args:
      - 'run deploy data-processor --image gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA --region europe-west4 --platform managed'

images:
- gcr.io/$PROJECT_ID/app-forwarder
- gcr.io/$PROJECT_ID/data-processor
