steps:
  - name: docker
    entrypoint: '/bin/sh'
    args:
      - -c
      - 'cd app-forwarder
         docker build -t gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA . &&
         docker tag gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA gcr.io/$PROJECT_ID/app-forwarder:$TAG_NAME &&
         docker tag gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA gcr.io/$PROJECT_ID/app-forwarder:latest'
  - name: docker
    entrypoint: '/bin/sh'
    args:
      - -c
      - 'cd app
         docker build -t gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA . &&
         docker tag gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA gcr.io/$PROJECT_ID/data-processor:$TAG_NAME &&
         docker tag gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA gcr.io/$PROJECT_ID/data-processor:latest'
images:
- gcr.io/$PROJECT_ID/pubsub-testbench/app-forwarder
- gcr.io/$PROJECT_ID/pubsub-testbench/data-processor
