# triggers on git tag
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: app-forwarder-build
    waitFor: ['-']
    dir: 'app-forwarder'
    args:
      - --dockerfile=Dockerfile
      - --destination=gcr.io/$PROJECT_ID/app-forwarder
      - --cache=true
      - --context=.
      - --cache-ttl=24h
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    waitFor: [app-forwarder-build]
    entrypoint: gcloud
    args: ['run', 'deploy', 'app-forwarder', '--image', 'gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA', '--region', 'europe-west4', '--platform', 'managed']

  - name: 'gcr.io/kaniko-project/executor:latest'
    id: data-processor-build
    waitFor: ['-']
    dir: 'data-processor'
    args:
      - --dockerfile=Dockerfile
      - --destination=gcr.io/$PROJECT_ID/data-processor
      - --cache=true
      - --context=.
      - --cache-ttl=24h
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    waitFor: [data-processor-build]
    entrypoint: gcloud
    args: ['run', 'deploy', 'data-processor', '--image', 'gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA', '--region', 'europe-west4', '--platform', 'managed']
