# triggers on git tag
steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: app-forwarder-build
    waitFor: ['-']
    dir: 'app-forwarder'
    args:
      - --dockerfile=Dockerfile
      - --destination=gcr.io/$PROJECT_ID/app-forwarder
      - --cache=true
      - --context=.
      - --cache-ttl=12h

  - name: 'gcr.io/kaniko-project/executor:latest'
    id: data-processor-build
    waitFor: ['-']
    dir: 'data-processor'
    args:
      - --dockerfile=Dockerfile
      - --destination=gcr.io/$PROJECT_ID/data-processor
      - --cache=true
      - --context=.
      - --cache-ttl=12h



  # - name: docker
  #   id: app-forwarder-build
  #   waitFor: ['-']
  #   entrypoint: '/bin/sh'
  #   dir: 'app-forwarder'
  #   args:
  #     - -c
  #     - 'docker build -t gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA . &&
  #        docker tag gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA gcr.io/$PROJECT_ID/app-forwarder:$TAG_NAME &&
  #        docker tag gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA gcr.io/$PROJECT_ID/app-forwarder:latest &&
  #        docker push gcr.io/$PROJECT_ID/app-forwarder'
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   waitFor: [app-forwarder-build]
  #   entrypoint: gcloud
  #   args: ['run', 'deploy', 'app-forwarder', '--image', 'gcr.io/$PROJECT_ID/app-forwarder:$SHORT_SHA', '--region', 'europe-west4', '--platform', 'managed']
  #
  # - name: docker
  #   id: data-processor-build
  #   waitFor: ['-']
  #   entrypoint: '/bin/sh'
  #   dir: 'data-processor'
  #   args:
  #     - -c
  #     - 'docker build -t gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA . &&
  #        docker tag gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA gcr.io/$PROJECT_ID/data-processor:$TAG_NAME &&
  #        docker tag gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA gcr.io/$PROJECT_ID/data-processor:latest &&
  #        docker push gcr.io/$PROJECT_ID/data-processor'
  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   waitFor: [data-processor-build]
  #   entrypoint: gcloud
  #   args: ['run', 'deploy', 'data-processor', '--image', 'gcr.io/$PROJECT_ID/data-processor:$SHORT_SHA', '--region', 'europe-west4', '--platform', 'managed']

# images:
# - gcr.io/$PROJECT_ID/app-forwarder
# - gcr.io/$PROJECT_ID/data-processor
