version: "3.3"
services:
  data-processor:
    build:
      context: data-processor
    environment:
      - PORT=8080
  app-forwarder:
    build:
      context: app-forwarder
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - REQUEST_TOPIC_ID=request-topic
      - PORT=8080
    ports:
      - 8080:8080
  publisher:
    build:
      context: publisher
    # ports:
    #   - 8081:8080
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - PUBSUB_PROJECT_ID=pubsub-demo
  pubsub:
    image: google/cloud-sdk:latest
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port", "0.0.0.0:8085"]
