version: "3.3"
services:
  app-forwarder:
    build:
      context: app-forwarder
    environment:
      - PORT=8080 # <- why even set this? It is completely invariable due to Cloud Run constraints.
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - DATA_PROCESSING_REQUEST_TOPIC_ID=data-processing-request
      - PROJECT_ID=bogus
    ports:
      - 8080:8080
  data-processor:
    build:
      context: data-processor
    environment:
      - PORT=8080
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - DATA_PROCESSING_RESPONSE_TOPIC_ID=data-processing-response
      - PROJECT_ID=bogus

  pubsub:
    image: google/cloud-sdk:latest
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port", "pubsub:8085"]
    # command: bash -c "
    #   gcloud beta emulators pubsub start --host-port 0.0.0.0:8085 &
    #   sleep 10 &&
    #   gcloud beta emulators pubsub env-init &&
    #   gcloud pubsub topics create data-processing-request-topic"
  pubsub-instructor:
    build:
      context: pubsub-instructor
    depends_on:
      - pubsub
    environment:
      - PROJECT_ID=bogus
      - PUBSUB_EMULATOR_HOST=pubsub:8085
      - DATA_PROCESSING_RESPONSE_TOPIC_ID=data-processing-response
      - DATA_PROCESSING_REQUEST_TOPIC_ID=data-processing-request
      - DATA_PROCESSING_REQUEST_PUSH_SUBSCRIPTION_URI=http://data-processor:8080/
    ports:
      - 8085:8085
