version: "3.4"

# define common environment variables
x-pubsub-linked-subsystem: &pubsub-linked-subsystem
  environment:
    - PROJECT_ID=bogus # <- emulator requires valid, but not necessarily existing projectname
    - PUBSUB_EMULATOR_HOST=pubsub:8085
    - DATA_PROCESSING_REQUEST_TOPIC=data-processing-request-topic
    - DATA_PROCESSING_REQUEST_SUBSCRIPTION=data-processing-request-subscription
    - DATA_PROCESSING_REQUEST_PUSH_SUBSCRIPTION_URI=http://data-processor:8080/
    - DATA_PROCESSING_RESPONSE_TOPIC=data-processing-response-topic

services: # Cloud Run ports are always 8080, so no variable necessary
  # emulates a GCP pubsub
  pubsub:
    image: google/cloud-sdk:latest
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port", "pubsub:8085"]
  # sets pubsub topics, subscriptions, etc.
  pubsub-instructor:
    <<: *pubsub-linked-subsystem
    build:
      context: pubsub-instructor
    depends_on:
      - pubsub

  # publishes a message. For example:
  # curl -X POST localhost:8080/ -d '{"text": "dev"}' -H "Content-Type: application/json"
  app-forwarder:
    <<: *pubsub-linked-subsystem
    build:
      context: app-forwarder
    ports:
      - 8080:8080
  # does something with the message, then publish
  data-processor:
    <<: *pubsub-linked-subsystem
    build:
      context: data-processor
